# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7671ff8682a62782622090840fe1bd70cf09a79b67fe54e94dba907a9116dd4208265dff902561357dae33902b877d2cd2346ae4f85db55dddfc1702395c6a87

test:
  secret_key_base: 67c0a8d8c1ba426403dba0480232d56dfae9883ba0e6ee092d0ac4e940ce5ef3de902e9fe9baa98da06b1b261011c20373b26f174e7b76ab8220d433c51f7b22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
